name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  uuid: ^4.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  injectable: ^2.3.2
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  build_runner:

flutter:
  uses-material-design: true
  generate: true
